version: 2.0
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - checkout
      - run: |
          git submodule sync
          git submodule update --init
      - add_ssh_keys:
          fingerprints:
            - "91:df:5c:72:e7:53:a0:64:63:47:f3:72:e5:76:27:4c"
      - run: git config --global user.name "kishimoto-banana"
      - run: git config --global user.email "drehbleistift@gmail.com"
      - deploy:
          name: Deploy to GitHub Pages
          command: ./deploy.sh
