version: 2.0
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - checkout
      # - add_ssh_kesys:
      #     fingerprints:
      #       - "b0:97:c0:2c:dc:bf:4b:c4:73:5d:e3:ee:ff:51:dd:a4"
      - run: git config --global user.name "circleci"
      - run: git config --global user.email "drehbleistift@gmail.com"
      - run:
          name: building profile page
          command: HUGO_ENV=production hugo -v
      # - run: rm -rf public
      # - run: git submodule add -b master git@github.com:kishimoto-banana/kishimoto-banana.github.io.github.io.git public
      - deploy:
          name: Deploy to GitHub Pages
          command: ./deploy.sh
