version: 2.1
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - checkout
      - run: apk Update && apk add git
      - run:
        name: building profile page
        command: HUGO_ENV=production hugo -v
      - deploy:
          name: Deploy to GitHub Pages
          command: ./deploy.sh
